image: gitpod/workspace-full

tasks:
  - name: Install Dependencies
    init: |
      # Install Solana
      sh -c "$(curl -sSfL https://release.solana.com/v1.17.9/install)"
      export PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH"
      echo 'export PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH"' >> ~/.bashrc
      
      # Install project dependencies
      npm install --legacy-peer-deps \
        @project-serum/anchor \
        @solana/wallet-adapter-base \
        @solana/wallet-adapter-react \
        @solana/wallet-adapter-react-ui \
        @solana/wallet-adapter-wallets \
        @solana/web3.js \
        next@latest \
        zustand

      # Install dev dependencies
      npm install -D \
        @types/node@latest \
        @types/react@latest \
        @types/react-dom@latest \
        typescript@latest
      
    command: |
      export PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH"
      solana config set --url devnet
      solana-keygen new --no-bip39-passphrase -o ~/.config/solana/id.json
      npm run dev

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public